# -*- coding: utf-8 -*-
"""Copy of Hotel Password Management system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFtI0DdCqfoHeQoap-AzqkFbBqVY6LBF
"""

def get_predefined_users():
    """Return a dictionary of 20 predefined usernames and passwords with Ghanaian names."""
    users = {
        'kwameAsante': 'password123',
        'amaBoateng': 'securePass45',
        'yawOfori': 'myPassword!',
        'akuaMensah': 'hotel2024',
        'kofiAdjei': 'guestUser@12',
        'adwoaAmoah': 'strongPass789',
        'yawOwusu': 'welcome2024',
        'afiaSarpong': 'checkIn88',
        'kwekuBediako': 'roomService99',
        'efuaAddo': 'staySecure123',
        'yawAmpofo': 'hotelGuest55',
        'afiaAcheampong': 'manager007',
        'kofiBaah': 'frontDesk@2024',
        'amaDanquah': 'cleanRoom123',
        'yawTetteh': 'freeBreakfast!',
        'efuaAgyeman': 'poolAccess2024',
        'yawObeng': 'vipGuest007',
        'amaNyarko': 'concierge2024',
        'kofiYeboah': 'luggageService88',
        'akuaDapaah': 'spaRelax@24'
    }
    return users

def hotel_login_system(users):
    """Login system for the hotel."""
    print("Welcome to the Hotel Password Manager")
    print("-------------------------------------")

    # Get the username and password from the user
    username = input("Enter your username: ")
    password = input("Enter your password: ")

    # Check if the username exists and the password matches
    if username in users and users[username] == password:
        print(f"\nLogin successful! Welcome, {username}.")
    else:
        print("\nLogin failed. Invalid username or password.")

if __name__ == "__main__":
    # Get the list of 20 predefined users
    predefined_users = get_predefined_users()
    print("Predefined Users Loaded.")

    # Start the hotel login system
    hotel_login_system(predefined_users)